#!/bin/sh

# @file: install
# @brief: install pushMySite
# @author: feihu1996.cn
# @date: 18-07-18
# @version: 1.0

# get install path from repl
echo 'Where do you want to install?'
read install_path

# create launch script
echo 'starting launch script ...'
touch pushMySite
chmod +x pushMySite
echo '#!/bin/sh' >> pushMySite
echo '' >>  pushMySite
echo '# @file: pushMySite' >> pushMySite
echo '# @brief: launch pushMySite script' >> pushMySite
echo '# @author: feihu1996.cn' >> pushMySite
echo '# @date: '$(date) >> pushMySite
echo '# @version: 1.0' >> pushMySite
echo '' >> pushMySite
echo 'if test $1 = --log' >> pushMySite
echo 'then' >> pushMySite
echo '    cat '$install_path/pushmysite.log >> pushMySite
echo 'else' >> pushMySite
echo '    cd '$install_path >> pushMySite
echo '    python3 pushMySite.py' >> pushMySite
echo 'fi' >> pushMySite
echo 'launch script has been created.'

# install
echo "starting install to $install_path ..."
mkdir -p $install_path
cp ./* $install_path/ -rfv
ln -fs $install_path/pushMySite /usr/bin/pushMySite
echo 'installed successfully!'

